version: "3"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    depends_on:
      - db
  db:
    image: postgis/postgis:12-3.0
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  deps:
  build:
  postgres:
